name: CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - feature/github-actions

jobs:
  terraform_lint:
    name: Terraform Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
      - name: Terraform Lint
        run: |
          terraform fmt --recursive --check terraform
          echo "Hello ${{ github.event.inputs.name }}!"